const messages = [
    {
      id: 1,
      primary: 'Brunch this week?',
      secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
      person: '/static/images/avatar/5.jpg',
    },
    {
      id: 2,
      primary: 'Birthday Gift',
      secondary: `Do you have a suggestion for a good present for John on his work
        anniversary. I am really confused & would love your thoughts on it.`,
      person: '/static/images/avatar/1.jpg',
    },
    {
      id: 3,
      primary: 'Recipe to try',
      secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
      person: '/static/images/avatar/2.jpg',
    },
    {
      id: 4,
      primary: 'Yes!',
      secondary: 'I have the tickets to the ReactConf for this year.',
      person: '/static/images/avatar/3.jpg',
    },
    {
      id: 5,
      primary: "Doctor's Appointment",
      secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
      person: '/static/images/avatar/4.jpg',
    },
    {
      id: 6,
      primary: 'Discussion',
      secondary: `Menus that are generated by the bottom app bar (such as a bottom
        navigation drawer or overflow menu) open as bottom sheets at a higher elevation
        than the bar.`,
      person: '/static/images/avatar/5.jpg',
    },
    {
      id: 7,
      primary: 'Summer BBQ',
      secondary: `Who wants to have a cookout this weekend? I just got some furniture
        for my backyard and would love to fire up the grill.`,
      person: '/static/images/avatar/1.jpg',
    },
];

const interested = [
  {
    id: 1,
    name: 'Brunch this week?',
    secondary: "",
    image: '/static/images/avatar/5.jpg',
    isHost: true,
  },
  {
    id: 2,
    name: 'Birthday Gift',
    secondary: "following",
    image: '/static/images/avatar/1.jpg',
    isHost: false,
  },
  {
    id: 3,
    name: 'Recipe to try',
    secondary: "following",
    image: '/static/images/avatar/2.jpg',
    isHost: false,
  },
  {
    id: 4,
    name: 'Yes!',
    secondary: "",
    image: '/static/images/avatar/3.jpg',
    isHost: true,
  },
  {
    id: 5,
    name: "Doctor's Appointment",
    secondary: "",
    image: '/static/images/avatar/4.jpg',
    isHost: false,
  },
  {
    id: 6,
    name: 'Discussion',
    secondary: "following",
    image: '/static/images/avatar/5.jpg',
    isHost: false,
  },
];

const going = [
  {
    id: 1,
    primary: 'Brunch this week?',
    secondary: "following",
    person: '/static/images/avatar/5.jpg',
    isHost: false,
  },
  {
    id: 2,
    primary: 'Birthday Gift',
    secondary: "",
    person: '/static/images/avatar/1.jpg',
    isHost: true,
  },
  {
    id: 3,
    primary: 'Recipe to try',
    secondary: "",
    person: '/static/images/avatar/2.jpg',
    isHost: false,
  },
  {
    id: 4,
    primary: 'Yes!',
    secondary: "following",
    person: '/static/images/avatar/3.jpg',
    isHost: true,
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary: "",
    person: '/static/images/avatar/4.jpg',
    isHost: true,
  },
  {
    id: 6,
    primary: 'Discussion',
    secondary: "following",
    person: '/static/images/avatar/5.jpg',
    isHost: false,
  },
  {
    id: 7,
    primary: 'Summer BBQ',
    secondary: "following",
    person: '/static/images/avatar/1.jpg',
    isHost: false,
  },
  {
    id: 8,
    primary: 'Brunch this week?',
    secondary: "following",
    person: '/static/images/avatar/5.jpg',
    isHost: false,
  },
  {
    id: 9,
    primary: 'Birthday Gift',
    secondary: "",
    person: '/static/images/avatar/1.jpg',
    isHost: true,
  },
  {
    id: 10,
    primary: 'Recipe to try',
    secondary: "",
    person: '/static/images/avatar/2.jpg',
    isHost: false,
  },
  {
    id: 11,
    primary: 'Yes!',
    secondary: "following",
    person: '/static/images/avatar/3.jpg',
    isHost: true,
  },
  {
    id: 12,
    primary: "Doctor's Appointment",
    secondary: "",
    person: '/static/images/avatar/4.jpg',
    isHost: true,
  },
  {
    id: 13,
    primary: 'Discussion',
    secondary: "following",
    person: '/static/images/avatar/5.jpg',
    isHost: false,
  },
  {
    id: 14,
    primary: 'Summer BBQ',
    secondary: "following",
    person: '/static/images/avatar/1.jpg',
    isHost: false,
  },
  {
    id: 15,
    primary: 'Brunch this week?',
    secondary: "following",
    person: '/static/images/avatar/5.jpg',
    isHost: false,
  },
  {
    id: 16,
    primary: 'Birthday Gift',
    secondary: "",
    person: '/static/images/avatar/1.jpg',
    isHost: true,
  },
  {
    id: 17,
    primary: 'Recipe to try',
    secondary: "",
    person: '/static/images/avatar/2.jpg',
    isHost: false,
  },
  {
    id: 18,
    primary: 'Yes!',
    secondary: "following",
    person: '/static/images/avatar/3.jpg',
    isHost: true,
  },
];

const mockData = {
  messages,
  interested,
  going,
}

export default mockData;